import type { ProductUpdate } from "./load";
import { latestVersion, sortByVersionDesc, unreadCount } from "./unread";
import type { ProductUpdatesSnapshot } from "./load";

/** Same notes as `0024` + `0025` + `0026` + `0027` + `0028` + `0029` + `0030` + `0031` + `0032` + `0033` + `0034` + `0035` + `0038` + `0040` + `0042` + `0044` + `0045` + `0047` + `0048` + `0049` + `0050` + `0052` + `0056` + `0057` migrations. Used when the table is not applied yet. */
export const BUNDLED_UPDATES: ProductUpdate[] = sortByVersionDesc([
  {
    id: "seed-1.27.0",
    version: "1.27.0",
    title: "Demande brouillon : e-mail ou téléphone",
    items: [
      "Sur le funnel public (/c et /embed), le visiteur choisit « Par e-mail » ou le téléphone pour envoyer sa demande.",
      "Après le premier envoi, il peut ajouter d’autres lignes au même dossier sans resaisir le contact.",
      "Une seule notification brief arrive dans la boîte commerciale au premier envoi — pas de mail au prospect, pas de second brief si on ajoute encore des lignes.",
      "Un dossier téléphone seul (sans e-mail) reste visible côté commercial ; la confirmation prospect n’est pas envoyée s’il n’y a pas d’e-mail.",
    ],
    releasedAt: "2026-09-23",
    createdAt: "2026-09-23T00:00:00.000Z",
  },
  {
    id: "seed-1.26.0",
    version: "1.26.0",
    title: "Devis reçus depuis WordPress",
    items: [
      "Un visiteur qui envoie une demande depuis le site WordPress (plugin QuoteBuilder) crée un devis dans le dashboard, en statut Nouveau, origine Site Web.",
      "Les lignes se rattachent aux produits déjà synchronisés (y compris les variations WooCommerce) ; un produit inconnu garde le nom envoyé.",
      "L’équipe est prévenue comme pour un brief funnel (notification in-app + email brief) ; le prospect n’est pas relancé automatiquement.",
      "Un même envoi n’est pas créé deux fois.",
      "Dans le plugin, ajouter deux fois le même produit simple met à jour la quantité au lieu de dupliquer la ligne.",
    ],
    releasedAt: "2026-09-23",
    createdAt: "2026-09-23T00:00:00.000Z",
  },
  {
    id: "seed-1.25.0",
    version: "1.25.0",
    title: "Mode d'emploi sur la fiche produit B2B",
    items: [
      "La fiche produit a un emplacement dédié mode d'emploi : notice courte, documents (manuel, conformité, garantie) et photos d'instruction, à côté des rôles photo / plan / usage.",
      "Sync Woo intelligente : métas _qb_manual / certificat / garantie, téléchargements et indices de nom de fichier — sans copier la description HTML, sans effacer une notice déjà saisie.",
      "Dans l'admin produit, vous éditez la notice, les liens et le rôle Notice sur chaque image.",
      "Le funnel public, l'embed, le brief devis et la page boutique affichent un bloc « Mode d'emploi » compact dès qu'il y a quelque chose à montrer.",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.24.0",
    version: "1.24.0",
    title: "Fiche technique dans le brief et le devis",
    items: [
      "Sur /c/… et /embed/…, les produits déjà au devis affichent leur fiche (charge, hauteur, profondeur, matériau, délai) dans le brief ; l’étape personnaliser montre le même tableau.",
      "Les valeurs et unités sont en police monospace ; un produit sans specs n’affiche rien.",
      "Avec ?add= / ?product=, les specs du produit sont copiées sur le devis (et la chip de gamme est sélectionnée quand le nom ou les tags le permettent).",
      "Le dossier commercial et le PDF reprennent cette fiche sous « Fiche technique ».",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.23.0",
    version: "1.23.0",
    title: "Fiche produit B2B : specs et médias classés",
    items: [
      "Sur la fiche produit du catalogue, charge, hauteur, profondeur, matériau et délai s’éditent en champs dédiés.",
      "Les images de la galerie se classent en photo produit, plan ou usage ; la carte garde la photo produit, plan et usage apparaissent en miniatures.",
      "Dans le funnel public, l’embed et la page boutique, le tableau ou les puces de specs s’affichent depuis la fiche produit.",
      "La sync WooCommerce lit le rôle de chaque média (_qb_media_role, sinon alt / titre / nom de fichier) sans écraser un rôle déjà enregistré.",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.22.0",
    version: "1.22.0",
    title: "Titres commerçant sur les funnels publics et embeds",
    items: [
      "Sur /c/… et /embed/…, l’onglet et le partage Open Graph affichent le devis du commerçant (ex. « Devis rayonnage — Quickly International »), plus le slogan marketing QuoteBuilder.",
      "Un nom de funnel déjà au nom du commerçant est conservé tel quel.",
      "Les embeds restent noindex, canoniques vers /c/…, et n’embarquent plus le JSON-LD produit QuoteBuilder.",
      "Le shortcode / widget.js titre l’iframe « Devis … » (ou data-title) et fixe une hauteur explicite (défaut 720px).",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.21.0",
    version: "1.21.0",
    title: "URL WooCommerce sans doubler le catalogue",
    items: [
      "Sur Boutiques → fiche connexion WooCommerce, un champ URL permet de pointer une autre adresse (changement de domaine ou clone) sans créer une deuxième connexion.",
      "Les clés REST déjà enregistrées sont testées avant le changement ; si elles ne répondent pas, l’URL actuelle reste en place avec un message clair.",
      "Quand une organisation n’a qu’une connexion Woo, reconnecter le plugin WordPress depuis une autre URL met à jour cette connexion au lieu d’importer un second catalogue.",
      "Une synchronisation restée « en cours » plus de 6 minutes est marquée interrompue, pour pouvoir relancer sans blocage.",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.20.0",
    version: "1.20.0",
    title: "Sync Woo : catégories plus précises",
    items: [
      "À la synchro WooCommerce, chaque produit prend sa catégorie la plus précise (la feuille), plus le parent générique.",
      "Les libellés trop vagues (« Divers », « Non classé ») sont ignorés s’il existe une catégorie métier.",
      "Les unités de dimensions et de poids suivent les réglages produits de la boutique.",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.19.0",
    version: "1.19.0",
    title: "Specs produit structurées",
    items: [
      "Dans le funnel et l’embed, le catalogue public expose des specs structurées (charge, hauteur, profondeur, matériau, délai), séparées des choix du prospect (couleur, largeur, niveaux…).",
      "La synchro WooCommerce écrit ces specs depuis les attributs, dimensions et meta (charge, hauteur, profondeur, matériau, délai), sans mélanger avec les variations/choix.",
      "Les specs déjà enregistrées en base complètent le payload quand la clé n’est pas déjà dans les options.",
      "Un choix « Hauteur » côté Woo peut aussi alimenter la hauteur max affichée en spec.",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.18.0",
    version: "1.18.0",
    title: "Préremplissage du funnel depuis l’URL",
    items: [
      "Sur /c/… et /embed/… (et via le shortcode WordPress), ?besoin= préremplit les chips de gamme dès l’ouverture.",
      "?add= ou ?product= sélectionne une chip ou ajoute un produit du catalogue (id, SKU, id externe ou nom exact) avec quantité 1.",
      "Les réponses déjà saisies sont conservées : les paramètres s’ajoutent sans écraser.",
      "Les boutons « + Ajouter à mon devis » du site (ex. Hostinger) peuvent ouvrir le parcours déjà rempli.",
    ],
    releasedAt: "2026-09-22",
    createdAt: "2026-09-22T00:00:00.000Z",
  },
  {
    id: "seed-1.17.0",
    version: "1.17.0",
    title: "Espace membres : un lien pour tous les devis",
    items: [
      "Créez un espace membres comme une boutique : constructeur, documents, plugins, lien public.",
      "Après un devis, le client retrouve toutes ses demandes au même endroit (email + PIN).",
      "Ajoutez des documents et des liens (plugin WordPress, notices) visibles une fois connecté.",
    ],
    releasedAt: "2026-09-14",
    createdAt: "2026-09-14T00:00:00.000Z",
  },
  {
    id: "seed-1.16.0",
    version: "1.16.0",
    title: "MCP distant : Claude et ChatGPT",
    items: [
      "Un serveur MCP hébergé est disponible sur /api/mcp : Claude, ChatGPT et Cursor parlent au même pipeline devis.",
      "ChatGPT (web) se connecte en OAuth (Paramètres → API & webhooks). Claude Desktop garde npx ou la clé Bearer.",
      "Les outils devis (créer, lister, statut) sont actifs sur le serveur distant, sans flag.",
    ],
    releasedAt: "2026-09-14",
    createdAt: "2026-09-14T00:00:00.000Z",
  },
  {
    id: "seed-1.15.0",
    version: "1.15.0",
    title: "Chat boutique : la conversation reste ouverte",
    items: [
      "Entrée envoie le message (Maj+Entrée pour une nouvelle ligne).",
      "Le fil et l’onglet Chat restent ouverts après chaque réponse IA ; le canvas se met à jour sans tout remonter.",
      "Clique un bloc, l’en-tête ou le pied : le Chat cible cette zone (plus de réécriture de toute la boutique).",
      "Inspecteur dédié pour le nom et les liens du menu depuis l’en-tête ou le pied, avec raccourci Chat.",
      "Aperçu en direct des étapes IA, image en pièce jointe, et annulation du dernier tour.",
    ],
    releasedAt: "2026-09-12",
    createdAt: "2026-09-12T00:00:00.000Z",
  },
  {
    id: "seed-1.14.0",
    version: "1.14.0",
    title: "Devis depuis Claude (MCP)",
    items: [
      "Avec Claude Desktop et le flag MCP devis, tu peux créer un devis, lister les demandes et lire le statut sans ouvrir le dashboard.",
      "La création depuis Claude n’envoie pas les emails d’autopilote par défaut ; active-les seulement si tu veux les relances.",
      "Le statut renvoyé reste allégé : score, assignation et funnel, sans notes ni réponses internes.",
      "Documenté côté API / MCP (Paramètres → API & webhooks et docs MCP).",
    ],
    releasedAt: "2026-09-12",
    createdAt: "2026-09-12T00:00:00.000Z",
  },
  {
    id: "seed-1.13.1",
    version: "1.13.1",
    title: "Liens boutique vers le devis restent dans la vitrine",
    items: [
      "Les anciens liens vers le funnel /c/… avec indication boutique redirigent vers le devis intégré /b/…/devis (boutique publiée et liée).",
      "Les paramètres utiles (produit, UTM, etc.) sont conservés.",
      "Sans boutique (ou boutique inconnue / non publiée / non liée), le funnel /c/ reste inchangé.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.13.0",
    version: "1.13.0",
    title: "Catalogue boutique = seule source du devis intégré",
    items: [
      "Sur /b/…/devis, produits, suggestions et parcours viennent uniquement du catalogue relié à cette boutique.",
      "Plus de mélange avec le catalogue d’une autre boutique ou d’un funnel org-wide.",
      "Catalogue manquant ou inactif : message clair « Catalogue de cette boutique introuvable. ».",
      "Les parcours /c/ (hors boutique) restent inchangés.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.12.0",
    version: "1.12.0",
    title: "Funnel devis aux couleurs de la boutique",
    items: [
      "Sur /b/…/devis, le parcours de devis reprend l’accent, le fond et le texte de la vitrine.",
      "Boutons (Continuer, Envoyer, Chat, Sauvegarder, Voir le devis) et chrome d’étapes suivent le thème boutique.",
      "Le catalogue intégré utilise aussi les accents de la boutique.",
      "Les parcours /c/, embed et CRM restent inchangés (thème funnel classique).",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.11.0",
    version: "1.11.0",
    title: "Devis intégré dans la boutique",
    items: [
      "Sur la vitrine publique, « Devis » et « Ajouter au devis » restent dans la boutique (/b/…/devis) au lieu d’ouvrir le funnel /c/….",
      "La page devis garde le chrome boutique (nav, thème --shop-*).",
      "Sans configurateur relié : message clair + lien vers le catalogue (plus de crash).",
      "Sitemap, JSON-LD produit et llms.txt pointent vers l’URL devis de la boutique.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.10.0",
    version: "1.10.0",
    title: "Templates boutique par secteur",
    items: [
      "Trois bases prêtes à l’emploi : menuiserie, soins (skincare) et stock B2B.",
      "Chaque template a son thème, son rythme de page et ses textes métier.",
      "Choix du modèle dans la boîte de création de boutique (cartes dédiées + autres secteurs).",
      "Le Chat IA reprend le vocabulaire et les images du template choisi.",
      "La boutique reste en demande de devis (pas de checkout).",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.9.3",
    version: "1.9.3",
    title: "Inspecteur boutique : padding et marges appliqués",
    items: [
      "Padding et marge saisis dans l’inspecteur s’appliquent enfin sur le canvas (les nombres sans unité deviennent des px).",
      "Steppers +/− pour padding, marge, taille, graisse, top, left, z-index, arrondi, hauteur min et gutter.",
      "Les styles de l’inspecteur passent devant les presets vitrine (police, couleur, graisse).",
      "Saisie au clavier inchangée ; les steppers ajustent au clic.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.9.2",
    version: "1.9.2",
    title: "Menu mobile boutique publique réparé",
    items: [
      "Sur téléphone, le menu hamburger de la vitrine s’ouvre en plein écran (plus de tiroir coupé).",
      "Tous les liens (Accueil, Catalogue, etc.) restent visibles et utilisables, y compris avec encoche.",
      "Zones de tap plus confortables sur les liens empilés.",
      "Moins de défilement latéral accidentel sur la page boutique.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.9.1",
    version: "1.9.1",
    title: "Boutiques Chat IA : lien public dès la création",
    items: [
      "Après le premier échange avec le Chat IA, la boutique est publiée automatiquement.",
      "L’URL publique /b/… fonctionne tout de suite (plus de page introuvable en brouillon).",
      "Création depuis un modèle : reste en brouillon jusqu’au bouton Publier.",
      "La vitrine publique est rafraîchie à chaque sauvegarde, publication ou message Chat IA.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.9.0",
    version: "1.9.0",
    title: "Notes de version dans le dashboard",
    items: [
      "Nouvelle page Support → Mises à jour pour parcourir les nouveautés produit.",
      "Un badge non lu apparaît dans le menu Support jusqu’à l’ouverture.",
      "Accès aussi depuis Paramètres.",
      "Les versions non lues affichent une pastille « Nouveau ».",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.8.0",
    version: "1.8.0",
    title: "Confirmation et brief T+0",
    items: [
      "Les templates confirmation prospect et brief commercial sont créés pour chaque espace, y compris les existants.",
      "Le parcours demande envoie l’email T+0 même si ces templates manquaient.",
    ],
    releasedAt: "2026-09-11",
    createdAt: "2026-09-11T00:00:00.000Z",
  },
  {
    id: "seed-1.7.0",
    version: "1.7.0",
    title: "Automatisations plus fiables",
    items: [
      "Un changement de statut peut relancer le parcours sur la même demande.",
      "L’abandon tient compte des heures, pas seulement des minutes.",
      "Un devis gagné ou perdu arrête le parcours.",
    ],
    releasedAt: "2026-09-10",
    createdAt: "2026-09-10T00:00:00.000Z",
  },
]);

export const UPDATES_SEEN_COOKIE = "qb-updates-seen";

export function snapshotFromEntries(
  entries: ProductUpdate[],
  lastSeenVersion: string | null,
  source: ProductUpdatesSnapshot["source"],
): ProductUpdatesSnapshot {
  return {
    entries,
    lastSeenVersion,
    latest: latestVersion(entries),
    unread: unreadCount(entries, lastSeenVersion),
    source,
  };
}
