export type MarketingRoute = {
  path: string;
  changeFrequency: "weekly" | "monthly" | "yearly";
  priority: number;
  /** Date ISO si la route n’est pas un article (les articles prennent `publishedAt`). */
  lastModified?: string;
};

/** Public marketing URLs that return 200 and should be indexed. */
export const MARKETING_ROUTES: MarketingRoute[] = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/fonctionnalites", changeFrequency: "weekly", priority: 0.9 },
  { path: "/fonctionnalites/funnel", changeFrequency: "monthly", priority: 0.8 },
  { path: "/fonctionnalites/catalogue", changeFrequency: "monthly", priority: 0.8 },
  { path: "/fonctionnalites/ads", changeFrequency: "monthly", priority: 0.7 },
  { path: "/fonctionnalites/demandes", changeFrequency: "monthly", priority: 0.8 },
  { path: "/fonctionnalites/autopilote", changeFrequency: "monthly", priority: 0.8 },
  { path: "/fonctionnalites/espace-prospect", changeFrequency: "monthly", priority: 0.7 },
  { path: "/fonctionnalites/stats", changeFrequency: "monthly", priority: 0.7 },
  { path: "/fonctionnalites/equipe", changeFrequency: "monthly", priority: 0.6 },
  { path: "/fonctionnalites/integrations", changeFrequency: "monthly", priority: 0.8 },
  { path: "/comment-ca-marche", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-rayonnage-stockage", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-menuiserie-sur-mesure", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-location-evenementiel", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-agencement-bureau", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-stores-fermetures", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-cuisine-equipee", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-cloture-portail", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-pergola-terrasse", changeFrequency: "monthly", priority: 0.8 },
  { path: "/secteurs/funnel-devis-pompe-chaleur-chauffage", changeFrequency: "monthly", priority: 0.8 },
  { path: "/tarifs", changeFrequency: "weekly", priority: 0.9 },
  { path: "/a-propos", changeFrequency: "monthly", priority: 0.6 },
  { path: "/blog", changeFrequency: "weekly", priority: 0.8 },
  {
    path: "/blog/envoyer-devis-lien-securise-vs-pdf-email",
    changeFrequency: "monthly",
    priority: 0.8,
  },
  {
    path: "/blog/recevoir-demandes-devis-wordpress-quotebuilder",
    changeFrequency: "monthly",
    priority: 0.8,
  },
  { path: "/blog/bibliotheque-lignes-kits-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/remise-commerciale-marge-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/preremplir-devis-url-parametres", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/fiche-produit-b2b-devis-unifie", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/acomptes-echeances-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/validite-expiration-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/options-variantes-alternatives-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/signature-acceptation-devis-en-ligne-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/revue-pipeline-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/centraliser-demandes-devis-multi-canaux", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/versions-historique-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/assignation-sla-demande-devis-equipe", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/qualifier-demande-devis-avant-chiffrage", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/creer-devis-avec-claude-mcp", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/visite-guidee-parcours-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/relancer-devis-hot-depuis-dossier", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/delai-reponse-demande-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/template-boutique-en-ligne-menuiserie-devis", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/devis-en-ligne-integre-boutique", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/score-demande-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/configurateur-devis-vs-excel-pdf", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/pourquoi-les-devis-meurent-sans-relance", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/formulaire-contact-vs-funnel-devis-b2b", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog/installer-widget-devis-wordpress-javascript", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/sync-catalogue-woocommerce-shopify-parcours-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils", changeFrequency: "monthly", priority: 0.6 },
  { path: "/outils/cout-devis-non-relance", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/generateur-sequence-relances", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/score-brief-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/simulateur-taux-conversion-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/calculateur-capacite-equipe-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/estimateur-temps-chiffrage-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/simulateur-impact-remise-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/simulateur-roi-logiciel-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/simulateur-taux-acceptation-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/estimateur-cout-brief-incomplet", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/simulateur-cout-devis-expires", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/calculateur-acompte-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/estimateur-gain-temps-catalogue-devis", changeFrequency: "monthly", priority: 0.7 },
  { path: "/outils/calculateur-seuil-remise-marge", changeFrequency: "monthly", priority: 0.7 },
  {
    path: "/outils/generateur-url-prefill-devis",
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-09-22",
  },
  {
    path: "/outils/estimateur-leads-formulaire-vs-funnel-wp",
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-09-23",
  },
  {
    path: "/outils/estimateur-cout-devis-pdf-seuls",
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-09-24",
  },
  { path: "/legal/cgu", changeFrequency: "yearly", priority: 0.3 },
  { path: "/legal/confidentialite", changeFrequency: "yearly", priority: 0.3 },
];
