#!/usr/bin/env bash
# Cloud Agent install: idempotent dependency refresh + public dev env.
# Secrets (SUPABASE_SERVICE_ROLE_KEY, ANTHROPIC_API_KEY, RESEND_API_KEY, ...)
# are injected as environment variables by Cloud Agent secrets and are never
# written here. This only materializes the PUBLIC Supabase values so the dev
# server and auth middleware read a consistent config.
set -euo pipefail

cd "$(dirname "$0")/.."

npm ci

ENV_FILE=".env.local"
PUBLIC_URL="https://spgskgtycqxjziwjpjol.supabase.co"
PUBLIC_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZ3NrZ3R5Y3F4anppd2pwam9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzNDc4MDAsImV4cCI6MjEwMzkyMzgwMH0.2dtLyVZtpPGqWkCgaSj_Dim-efANRg-IVN01OJDAd0o"

# Rewrite the public block each run so the file stays in sync with the repo
# defaults. Next.js does not override real environment variables (injected
# secrets) with .env.local, so this is safe alongside Cloud Agent secrets.
cat > "$ENV_FILE" <<EOF
# Generated by .cursor/install.sh — public (non-secret) Supabase config.
# Server secrets come from Cloud Agent secrets, injected as env vars.
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-$PUBLIC_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$PUBLIC_ANON_KEY}
NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
EOF

echo "install.sh: dependencies installed and $ENV_FILE written."
